### ISSUE TITLE
Output a DID spec compatible document after resolution

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree#512] opened 2020-03-30 21:21 UTC
e.g.
```javascript
{
  "@context": [
    "https://w3id.org/did/v0.11",
    {
      "@base": "did:example:123"
    }
  ],
  "id": "did:example:123",
  "publicKey": [
    {
      "id": "#z6MksHh7qHWvybLg5QTPPdG2DgEjjduBDArV9EF9mRiRzMBN",
      "type": "Ed25519VerificationKey2018",
      "controller": "",
      "publicKeyBase58": "DqS5F3GVe3rCxucgi4JBNagjv4dKoHc8TDLDw9kR58Pz"
    }
  ],
  "service": [
    {
      "id": "#profile-image",
      "type": "ProfileImage",
      "serviceEndpoint": "https://profile.com/bob/profile.jpg"
    }
  ]
}
```

**Comment by OR13** [comment] 2020-03-30 21:29
Support for this was proved here: https://github.com/w3c/did-core-registries/pull/24

We may want to add clear language that when supplying key material for use with VCs, the full URI MUST be supplied... for example:

```
  const key = new Ed25519KeyPair({
    "id": "did:example:123#z6MkpzW2izkFjNwMBwwvKqmELaQcH8t54QL5xmBdJg9Xh1y4",
    "type": "Ed25519VerificationKey2018",
    "privateKeyBase58": "2m6scGwwRf4n79LmhhNKHhqcdTM2SMzosYhFXH7NStnKrwTVmNYztwNbfK3adDPNgmoZE8tt2FC9WqkBD77rRtXC",
    "publicKeyBase58": "BYEz8kVpPqSt5T7DeGoPVUrcTZcDeX5jGkGhUQBWmoBg"
  });
```

...

```
  const signed = await jsigs.sign(
    { ...document },
    {
      documentLoader,
      suite: new Ed25519Signature2018({
        key,
        date: "2019-12-11T03:50:55Z"
      }),
      purpose: new AssertionProofPurpose(),
      compactProof: false
    }
  );
````

**Comment by OR13** [comment] 2020-03-31 16:56
I think this issue is a dupe of: https://github.com/decentralized-identity/sidetree/issues/368

**Closed** 2020-04-06 18:03 UTC
Labels: beta, bug
