### ISSUE TITLE
Consider revising operation structure to be a JWT (Currently it is a JWS)

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/sidetree#146] opened 2019-03-23 19:15 UTC
The structure of an operation is loosely equivalent to a JWT, but operations are not JWTs, the property `signingKeyId` is extraneous since the header requires a `kid` property.

The use of base64url encoding seems excessive as well.

Why not make operations JWTs or Signed JSON-LD. Here are 2 examples which seem much simpler to me:

batchFile.json

```
{
  "operations": [
    "eyJhbGci(...).eyJzdWIiOiIxMjM0NTY3ODkw(...).SflKxwRJSM(...)"
  ]
}
```

decoded operation:

```
header = {"typ": "JWT", "alg": "ES256K"}
payload = {"kid":"#key1", "operation":"create", "payload": {doc | patch}, ...}
signature = ...
```
No need to for double base64url encoding, and the operation is a valid JWT.

Alternatively,

```
{
  "@context": [
    "https://www.w3.org/ns/sidetree",
    "https://w3id.org/security/v1"
  ],
  "@type": "Create",
  "object": {
    "@type": "DIDDocument",
    "content": { ... }
  },
  "signature": {
    "type": "EcdsaKoblitzSignature2016",
    "created": "2019-03-23T19:09:30Z",
    "creator": "ecdsa-koblitz-pubkey:020d79074ef137d4f338c2e6bef2a49c618109eccf1cd01ccc3286634789baef4b",
    "signatureValue": "IJiRAeoW9lPgDGldrZ4wQ5XWXaP5yJu/0a+RuHePg09HIAQgF/9B+6cplsJEXrY3AHB+RsuEOw9gUZhs3hp+TvQ="
  }
}
```

JWTs will be smaller, but JSON-LD is more flexible and human readable, and you will probably want a more compact binary encoding for json objects eventually anyway.

**Comment by thehenrytsai** [comment] 2019-03-25 18:34
Hey @OR13,

Thanks for looking at the operation structure in detail, it's great to have another pair of eyes at this.

I am breaking down this issue in sections:

* Remove `signingKeyId` property in operation structure.

  Agree with you. I believe `signingKeyId` is already removed, it has been superseded by `kid` as you suggested, protocol.md doesn't have a reference to it. Let me know if you find otherwise and where.

* Use JWT over JWS JSON.

  I have no objection on using JWT in principle, however, since JWT requires all headers to be signed and currently Sidetree by design allows `proofOfWork` to be unsigned, JWT is not a viable choice. Keep in mind that JWS is otherwise very similar to a JWT, after all, a JWT is a JWS (assuming it is not a JWE).

* Use of JSON-LD over JWS JSON.

  This is indeed a possibility, but this would not avoid the "double encoding" that you pointed out since the structure will be in JSON just like JWS JSON. Encoding the operations makes the Merkle root hash calculation much more robust (as we touched on in the other discussion https://github.com/decentralized-identity/sidetree-core/issues/105). The main benefit of JWS is obviously the standardized signature computation and verification. Also I have perf tested the batch file deserializationa/deserialization and found that the cost of encoding/decoding is practically negligible in comparison to other computation such as signature verification and even JSON  serialization.

**Comment by OR13** [comment] 2019-03-25 19:36
Thanks, regarding `signingKeyId`, I had been coding example payloads and come across it, and was then very confused when comparing to the protocol. 

I've been ignoring `proofOfWork` since its not implemented, but this makes more sense now. 

The issue is that a client might not do the `proofOfWork` , but they still need to sign their operation. 

In the case they do not, the operation header must be unsigned when anchored, and are trusting the node was honest and did the PoW check, when the node signs the ledger transaction, the node is explicitly signing the anchorFile hash, and implicitly signing the batch of operations which contain work done by the node or clients.

The question becomes, how is `proofOfWork` used.... in the case that a client provides it, its used to trust their operation was honest. In the case the node generates it, its used to show the node is honest, this means the PoW needs to be checked (during resolution?) and if its found to be bad only the node can be blamed since the client has not signed the proof of work, the node could theoretically replace the work with something that would fail (dishonest node)... 

I gather this is why the ethereum sidetree discussion surrounding staking comes up. They are assuming you cannot trust a sidetree node... is sidetree permissioned or permissionless? Seems permissioned given the dependency on IPFS, storage is not free.

As a client, I'd rather the node not be able to tamper with my work (I want to sign it), when the node validates my work, they will implicitly sign it when the batch is anchored. 

Could a node provide a `proofOfWork` for all operations that were lacking and include the proof with the batchFile? this is already what is happening, its just done per operation in the batchFile.

**Comment by thehenrytsai** [comment] 2019-03-26 00:06
Thanks @OR13,

Sorry for the confusion. I just filed issue #147 to updated outdated Base64URL encoded example in protocol.md.

Adding @csuwildcat regarding the PoW. We have yet to figure out the exact algorithm of PoW so please comment on issue #25 directly if you have any thoughts and suggestions, they will be valued! @csuwildcat and I have been actively discussing PoW's approach however. On the high-level, you are right, current design favors PoW to be supplied either by operation requester or the Batch Writer (in a Sidetree node), and it would be done by populating the `proofOfWork` unsigned header in the JWS. The operation requester always has to sign the operation request payload.

The Observer (in a Sidetree node) will validate the PoW without the (need of) knowledge of whom performed the PoW for each operation. The current thinking is that if the PoW is invalid for one operation, the entire batch is deemed invalid, so it is in the Batch Writer's interest to ensure that PoW is correct for the entire batch before it is anchored.

I do not want to hijack this thread too much for PoW, so if we continue the discussion on PoW, feel free to directly do so in issue #25 and I can close this issue.

**Comment by OR13** [comment] 2019-05-06 20:28
I'm closing this for now.

**Comment by csuwildcat** [comment] 2019-07-10 19:21
Given we are not using PoW as the flow control method any longer, and will need values to be protected in the header, I would like to reopen this issue and move that direction. This will come into play as we implement that DDoR/fast check solution being formulated in https://github.com/decentralized-identity/sidetree/issues/252

**Comment by OR13** [comment] 2019-07-10 19:24
This allows for operations to be valid JWTs, since JWTs require signed headers.

Combined with https://tools.ietf.org/html/draft-ietf-cose-webauthn-algorithms-01

We could have a standards compliant JWT operation format, that could easily be extended to support other signature formats, ed25519, RSA, etc..

**Comment by OR13** [comment] 2020-03-20 18:37
@thehenrytsai are headers now signed?

**Comment by csuwildcat** [comment] 2020-03-31 17:00
I believe this has been fixed/accounted for - please confirm.

**Comment by OR13** [comment] 2020-03-31 21:52
@csuwildcat JWS !== JWT. but JWS do have signed headers... @thehenrytsai close this if headers are signed.

**Comment by isaacJChen** [comment] 2020-04-03 22:25
No longer applicable, only a portion of the request is signed.

**Closed by isaacJChen** 2020-04-03 22:25 UTC
Labels: pending-close
